name: app
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc_presentation: ^0.2.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  fluster: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  freezed: ^2.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.8
  latlong2: ^0.8.1
  map_launcher: ^2.4.0

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter  
  intl_utils: ^2.7.0
  lint: ^2.0.1
  mocktail: ^0.3.0
  patrol: ^1.0.4

flutter_intl:
  enabled: true

flutter:  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
  generate: true
  uses-material-design: true
