name: app
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter  
  lint: ^1.8.2

flutter_intl:
  enabled: true

flutter:  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
  uses-material-design: true
